### ISSUE TITLE
Python 3.9 OpenMM builds

### ISSUE THREAD

**Issue by tomgoddard** [openmm/openmm#3174]
Can we get Python 3.9 builds of OpenMM 7.5.1 on Linux, Mac and Windows?

Anaconda omnia-dev has only Python 3.8, 3.7 and 3.6 versions of OpenMM 7.5.1 even though Python 3.9 has been out since October 2020.

I am switching ChimeraX from Python 3.8 to 3.9 and if there is no OpenMM build we will not include it.

**Comment by jchodera** [comment]
Hi @tomgoddard!

The official [OpenMM 7.5.1 conda-forge builds](https://anaconda.org/conda-forge/openmm/files?version=7.5.1) include builds for Python 3.6 though 3.9 for multiple platforms (osx-64, osx-arm, linux-64, linux-aarch64, win-64, ppc64le). 

We only use the [omnia-dev](https://anaconda.org/omnia-dev/openmm/files) nightly dev builds for lightweight convenience testing. These are build from `master` every night, and should not be used or packaging releases.

Is there something else you need that is missing? If you need to compile OpenMM from scratch (which should work on these platforms) for linking, you can find [info here](http://docs.openmm.org/latest/userguide/library.html#compiling-openmm-from-source-code).

We're aware the docs are in need of improvement. @peastman and @Yoshanuikabundi have been working hard on this, but if you can point to the docs that led you (erroneously) to the `omnia-dev` nightly dev builds, we can make sure to fix those and clarify their purpose.

**Comment by tomgoddard** [comment]
Thanks!  Sorry I was looking in the wrong place for the OpenMM builds - dumb mistake.  This ticket can be closed.

**Comment by jchodera** [comment]
No worries! If you figure out what led you to the wrong place (e.g. docs, search results), we can try to improve this!

@peastman : What would you think of changing the description in the [dev build recipe](https://github.com/omnia-md/conda-dev-recipes/blob/master/recipes/openmm/meta.yaml#L106) to include a warning that these are nightly dev builds, and point to the real builds?

![image](https://user-images.githubusercontent.com/3656088/125541949-8cc9104d-1db4-4724-b448-3a5bb621c53a.png)

**Comment by tomgoddard** [comment]
I was using the development OpenMM daily build in the past before 7.5.0 was released and I simply kept using omnia-dev for getting builds, not realizing that the release builds were elsewhere.

**Comment by tomgoddard** [comment]
Perhaps I can get some advice about which build to use.  I see there are 12 OpenMM 7.5.1 windows builds offering 6 different versions of CUDA and 2 different versions of OpenCL.  For our ChimeraX distribution which should I include?  Our users have diverse CUDA / OpenCL installed.

**Comment by jchodera** [comment]
Could you tell us a bit more about how you're bundling OpenMM? Are you building a conda recipe for ChimeraX? Is this in conda-forge, or your own channel?

**Comment by tomgoddard** [comment]
We distribute the ChimeraX application on Windows, Linux and Mac including Python.  We release a new version (currently 1.2) about every 6 months.  We have considered distributing ChimeraX through Conda but are not currently doing that -- we have asked for funding in grant proposals to support that effort but none have been funded yet.  The most important use of OpenMM in ChimeraX is for ISOLDE, Tristan Croll's atomic model refinement program.  ISOLDE allows switching between CUDA, OpenCL and CPU OpenMM platforms.  CUDA is the fastest if the user's computer supports it.

**Comment by tomgoddard** [comment]
One more question.  What is the difference between these two Mac builds

	osx-64/openmm-7.5.1-py39h17f8b25_0_apple.tar.bz2
	osx-64/openmm-7.5.1-py39h17f8b25_1_apple.tar.bz2

They differ only in the _0_ or _1_ in the file name and the build info shows no differences in dependencies, only the one with 1 shows build_number: 1 while the one with the 0 shows no build_number in the info.  Is there any documentation on what different builds are available for Windows, Linux and Mac?  Something that says which CUDA versions are being supported and whether the Khronos OpenCL loader is necessary to use OpenCL would be helpful.

**Comment by peastman** [comment]
CUDA has binary compatibility between minor versions, but not major versions.  If a program is compiled again the CUDA 11.0 toolkit, it should work with any other 11.x version, but not any 10.x version.  If you want to support users who have a variety of CUDA versions installed, it unfortunately is necessary to provide multiple builds.

For the Mac builds, the conda recipe lists the Apple OpenCL first:

```
opencl_impl:  # [osx]
- apple       # [osx]
- khronos     # [osx]
```

So probably the build numbers are in the same order?  I don't know for sure though.

**Comment by tomgoddard** [comment]
The two osx-64 builds I mentioned both have "apple" in the file name which I believe means Apple opencl.  Two other osx-64 builds have khronos in the file name and use two different versions of Khronos opencl (2021.4.29 and 2020.12.18) reported in the info.  The two apple builds don't show any distinguishing info.  Still wondering whether to distribute OpenMM in ChimeraX with Apple or Khronos OpenCL on Mac and which Khronos version.  We are only making one distribution and the aim is to best support users with diverse hardware.

**Comment by peastman** [comment]
Use the Apple OpenCL version.  The only reason to use the other one is if you want to use a different implementation of OpenCL distributed by conda-forge.

**Comment by tomgoddard** [comment]
Thanks, I will use the Apple OpenCL version of OpenMM in ChimeraX on Mac.

For CUDA, if I use the OpenMM version with CUDA 11.2 will it work on a system that has installed CUDA 11.0 or 11.1?  I guess not.  So why would I not stay with CUDA 11.0 in OpenMM?  I guess there is some performance or bug fix advantage using OpenMM 11.1 or 11.2?  But if 11.2 will be used by the OpenMM with 11.0 why would it not get those advantages?  Is part of CUDA somehow statically linked into OpenMM?  Sorry for the dumb questions.  I know this is a generic CUDA issue, not specific to OpenMM.  But it would be helpful since OpenMM tries to support CUDA if some OpenMM documentation described the compatibility issues to help users who are not familiar with the mess that is CUDA.

**Comment by peastman** [comment]
When you install OpenMM, here is how it's at least supposed to work.  Conda looks at your driver and figures out the most recent CUDA version that it supports.  Then it automatically installs the corresponding `cudatoolkit` package, and an OpenMM version that is matched to that package.  To make that work, we need to have a separate package version for each CUDA version.  That's a quirk of conda.  For you that isn't necessary.  If you use the CUDA 11.0 build of OpenMM, it will work with any CUDA 11.x toolkit.  But it will not work with 10.x versions, or with 12.x once that is released.

> Is part of CUDA somehow statically linked into OpenMM?

CUDA is linked dynamically.  Newer versions will work as long as they maintain the same ABI as the version you compiled against.  They maintain ABI compatibility in newer minor releases (for example 11.0 to 11.1), but not major releases (like 10.x to 11.x).

**Comment by tristanic** [comment]
> CUDA has binary compatibility between minor versions, but not major versions. If a program is compiled again the CUDA 11.0 toolkit, it should work with any other 11.x version, but not any 10.x version. 

Is this true, though? If I `ldd` the `libOpenMMCudaCompiler.so` in `openmm-7.5.1-py39hdd8ad19_1.tar.bz2`, it's linking specifically to `libnvrtc.so.11.0`. In my CentOS-7 machine, if I do `yum whatprovides libnvrtc.so.11*` it reveals this is only provided by the `cuda-nvrtc-11-0*` packages, and there is no generic `libnvrtc.so.11` provided.

... or is it that if `libnvrtc` fails to load OpenMM falls back to spawning `nvcc` processes for the compilation?

**Comment by tristanic** [comment]
OK, confirmed for myself that's how things seem to work. In Linux if I have the 11.0 cuda and cublas libraries installed then `Platform.getPluginLoadFailures()` reports libOpenMMCudaCompiler.so fails to load but the CUDA platform as a whole remains functional. If I install cuda-nvrtc-11.0 then `Platform.getPluginLoadFailures()` reports a clean slate. If I understand correctly, this means that in Windows if the user has a "perfect match" version of CUDA then they don't need a separate compiler (i.e. Visual Studio) installed?

**Comment by tomgoddard** [comment]
Thanks for looking into this Tristan.  For the moment I put OpenMM with CUDA 11.2 in ChimeraX daily builds yesterday for Linux and Windows.  Not sure what happens if the user has CUDA 11.0 or 11.1 installed.  Can't use CUDA or is it able to use any 11.x runtime?

**Comment by peastman** [comment]
It's safer to use the 11.0 build.  That should certainly work with any 11.x version.  I can't make the same guarantee about using an earlier version than what it was built against.

**Comment by tomgoddard** [comment]
I think we shouldn't rely on guesses.  If we use CUDA and are distributing for it we should know (and document for users) exactly what the compatibility rules are.  Tristan mentions that on Windows if the CUDA patch version is not an exact match then it may require Visual Studio compilers.  Most users won't have Visual Studio and most ChimeraX users are on Windows.  Another consideration is we have seen ChimeraX bug reports when OpenMM gave an error

simtk.openmm.OpenMMException: Error compiling program: nvrtc: error: invalid
value for --gpu-architecture (-arch)  
https://www.rbvi.ucsf.edu/trac/ChimeraX/ticket/4888 <https://www.rbvi.ucsf.edu/trac/ChimeraX/ticket/4888>

which may be a just-in-time compiler bug in CUDA 11.0, fixed in 11.1.  So there are various factors that could influence the decision of which OpenMM CUDA version to distribute with ChimeraX.  And a bigger question is how can ChimeraX let the user get an OpenMM with CUDA matching what is installed on their system.  That could be doable if PyPi OpenMM packages existed, just install the right OpenMM when the user needs it.  But since ChimeraX is part of Conda and that is the only OpenMM distribution system we don't have a solution.

**Comment by tristanic** [comment]
I've updated my singularity container to build with Python 3.9.5 and CUDA 11.2.1... but despite my pulling the OpenMM source with `git checkout 7.5.1` it still reports its version as 7.5.0. @peastman  any help? Ignoring that issue, the resulting build works fine with ISOLDE in ChimeraX.

I finally have a reasonably clear space coming up in my calendar - will put some time into prototyping a PyPI-compatible build next week.

**Comment by jchodera** [comment]
@peastman: Perhaps it makes sense to sync up directly with @tomgoddard since you're in the same time zone?

@tomgoddard : A few points here:
* You should _always_ be able to fall back to OpenCL even if the CUDA plugin doesn't load correctly. The OpenCL library would be installed with the graphics card drivers, so if they're using ChimeraX with a graphics card with a GPU, it should work.
* Because it's a pain to install the CUDA toolkit, we have the `openmm` conda-forge package depend on the `cudatoolkit` conda-forge package to ensure we vendor the appropriate version the toolkit along with OpenMM to have the highest chance of CUDA working correctly. It's a very difficult problem to solve otherwise.
* I don't understand the point about requiring Visual Studio. That may be a red herring.
* I think I'm confused about this point: Are you building conda packages of ChimeraX, or building a binary distribution package?

**Comment by tristanic** [comment]
@jchodera the point about Visual Studio: if I understand correctly, the way building for CUDA works is as follows:

- OpenMM tries to `dlopen` `libOpenMMCudaCompiler`, which relies on `libnvrt` - which doesn't require a separate compiler to be installed, but _does_ need to match the CUDA version OpenMM was built against all the way down to the minor version number.
- If `libOpenMMCudaCompiler` fails to load, it falls back to building using `nvcc`, which only needs to match the major CUDA version but relies on the help of a system compiler. In Linux that's no problem since every distro has gcc, but in Windows it needs at least a minimal installation of Visual Studio (there may be other compiler options I don't know, but Visual Studio is the easiest)

Currently, if OpenMM hits the second option and doesn't find a compiler ISOLDE doesn't catch the error thrown by OpenMM - I'll fix that so that it gracefully falls back to using OpenCL. 

In terms of packages: ChimeraX can incorporate the conda MacOS and Windows builds straightforwardly enough by extracting from the tarball into the relevant positions in its own tree, but Linux requires a separate build for reasons we've discussed previously: the conda compiler is binary-incompatible with the `devtoolset-9` compiler used to build ChimeraX and ISOLDE. I have a singularity recipe that will do the build reasonably painlessly, but this approach still means that there is no route for users to update their OpenMM version without updating ChimeraX itself. The ideal solution would be to add `manylinux2010` PyPI packages to the OpenMM build pipeline.

**Comment by tristanic** [comment]
... make that `libnvrtc`, not `libnvrt`.

**Comment by peastman** [comment]
> despite my pulling the OpenMM source with git checkout 7.5.1 it still reports its version as 7.5.0.

Where are you seeing that number?  The code on the 7.5.1 tag specifies the version number correctly:

https://github.com/openmm/openmm/blob/a9cfd7fb9343e21c3dbb76e377c721328830a3ee/CMakeLists.txt#L166-L168

From there it gets propagated to `Platform::getOpenMMVersion()`.

**Comment by peastman** [comment]
The CUDA runtime compiler is redistributable.  You could bundle a copy of it instead of relying on the installed one.

https://docs.nvidia.com/cuda/eula/index.html#attachment-a

**Comment by tristanic** [comment]
Hmm... maybe I just didn't hit save after editing the build script to pull from 7.5.1 rather than branch_7.5. Re-running to double check.

**Comment by peastman** [comment]
That would work too.  The `7.5.1` tag points to the current head of `7.5_branch`.

**Comment by tristanic** [comment]
Ah - stupid of me. Script wasn't changing to the openmm directory after cloning and before doing `git checkout 7.5.1`, so the build was running on the master branch which is still set to 7.5.0. Fixed (and also made the script die on errors so this won't happen again).

**Comment by tristanic** [comment]
> The CUDA runtime compiler is redistributable. You could bundle a copy of it instead of relying on the installed one.
> 
> https://docs.nvidia.com/cuda/eula/index.html#attachment-a

That seems like a solid solution. My system currently has CUDA 11.0 installed (from Nvidia's RedHat cuda repo) so its own nvrtc won't work with the CUDA 11.2 OpenMM build. Note: that currently leads to an ugly traceback for me when OpenMM attempts to run `nvcc`, since it seems the repo doesn't provide `cuda_runtime.h`:

```
RuntimeError: Error launching CUDA compiler: 256
In file included from :0:0:
/usr/include/stdc-predef.h:40:1: fatal error: cuda_runtime.h: No such file or directory
#endif
```

Anyway, if I download the CUDA 11.2 libnvrtc and libnvrtc-builtins, and plop those into the Chimerax/lib directory it runs just fine.

I think the most robust approach for ISOLDE will be to have it check `Platform.getPluginLoadFailures()`, and fall back to OpenCL any time `libOpenMMCudaCompiler` fails to load.

**Comment by tristanic** [comment]
... and the great news is that with `libnvrtc.so.11.2` the kernel compilation is now faster for CUDA than OpenCL (and the simulations themselves are about 50% faster).

**Comment by tristanic** [comment]
> 
> since it seems the repo doesn't provide `cuda_runtime.h`:
> 

Scratch that. Something must have been a bit wonky with `yum` - `yum whatprovides *cuda_runtime.h` was returning nothing on Friday, but finds it fine today.

**Comment by tristanic** [comment]
So... if both `libnvrtc` and `libcudart` were bundled in, then it becomes pretty trivial to check at runtime whether the user's CUDA driver is sufficient and give them inline feedback on what version they need. Could even do it in pure Python using `ctypes` (example below for Linux). Worked fine with an ancient libcudart.so.6.5 I found in an old VMD installation, against CUDA 11.3 drivers - that is, the query via the runtime correctly gives 11030 as the version. 

```
def version_error(required_major_version, required_minor_version):
    raise RuntimeError(f'CUDA driver is too old. Please update to at least {required_major_version}.{required_minor_version}') 


import ctypes

nvrtc = ctypes.CDLL('libnvrtc.so')
major_rtc = ctypes.c_int32()
minor_rtc = ctypes.c_int32()
nvrtc.nvrtcVersion(ctypes.byref(major_rtc), ctypes.byref(minor_rtc))
major_rtc = major_rtc.value
minor_rtc= minor_rtc.value


cudart = ctypes.CDLL('libcudart.so')
cuda_ver = ctypes.c_int32()
err_code = cudart.cudaDriverGetVersion(ctypes.byref(cuda_ver))
if err_code == 35: #cudaErrrorInsufficientVersion
    version_error(major_rtc, minor_rtc)
elif err_code != 0:
    raise RuntimeError(f'Failed querying CUDA version. Is CUDA (>={major_rtc}.{minor_rtc}) installed correctly?')
cuda_ver = cuda_ver.value
major_ver = cuda_ver//1000
minor_ver = (cuda_ver-major_ver*1000)//10

if major_rtc > major_ver or minor_rtc > minor_ver:
    version_error(major_rtc, minor_rtc)

```

**Comment by jchodera** [comment]
```
    raise RuntimeError(f'Failed querying CUDA version. Is CUDA (>={major_rtc}.{minor_rtc}) installed correctly?')
```
But you still want to fall back to OpenCL gracefully even if CUDA is highly misconfigured, right? OpenCL should work just fine for many users, but you want to nudge them to install the right CUDA (if they want to) to get full acceleration...

**Comment by tristanic** [comment]
True enough. This was just a quick example implementation - the final logic would be a little different (but perhaps something along these lines could be incorporated into OpenMM to make `Platform.getPluginLoadFailures()` a bit more informative about why failures happened?).
________________________________
