### ISSUE TITLE
Unable to install from source using Numpy 2

### ISSUE THREAD

**Issue by lvotapka** [openmm/openmm#4684]
Hello Everyone,

I just wanted to bring this issue to attention, and highlight how I resolved the problem.

With new mamba environments, the latest version of numpy (v 2.1.1) is installed by default. When I attempt to install OpenMM 8.1.2 from source, the "make PythonInstall" step generates the following errors:

```
src/swig_doxygen/OpenMMSwig.cxx:7662:94: error: cannot convert ‘PyObject* {aka _object*}’ to ‘const PyArrayObject* {aka const tagPyArrayObject_fields*}’ for argument ‘1’ to ‘int PyArray_NDIM(const PyArrayObject*)’
         if (PyArray_Check(stripped) && PyArray_ISCARRAY_RO(stripped) && PyArray_NDIM(stripped) == 2 && PyArray_DIM(stripped, 1) == 3) {
                                                                                              ^
src/swig_doxygen/OpenMMSwig.cxx:7662:127: error: cannot convert ‘PyObject* {aka _object*}’ to ‘const PyArrayObject* {aka const tagPyArrayObject_fields*}’ for argument ‘1’ to ‘npy_intp PyArray_DIM(const PyArrayObject*, int)’
         if (PyArray_Check(stripped) && PyArray_ISCARRAY_RO(stripped) && PyArray_NDIM(stripped) == 2 && PyArray_DIM(stripped, 1) == 3) {
                                                                                                                               ^
src/swig_doxygen/OpenMMSwig.cxx:7663:45: error: cannot convert ‘PyObject* {aka _object*}’ to ‘const PyArrayObject* {aka const tagPyArrayObject_fields*}’ for argument ‘1’ to ‘int PyArray_TYPE(const PyArrayObject*)’
             int type = PyArray_TYPE(stripped);
                                             ^
src/swig_doxygen/OpenMMSwig.cxx:7664:49: error: cannot convert ‘PyObject* {aka _object*}’ to ‘const PyArrayObject* {aka const tagPyArrayObject_fields*}’ for argument ‘1’ to ‘npy_intp PyArray_DIM(const PyArrayObject*, int)’
             int length = PyArray_DIM(stripped, 0);
                                                 ^
In file included from /home/lvotapka/openmm/openmmapi/include/openmm/State.h:35:0,
                 from /home/lvotapka/openmm/openmmapi/include/openmm/Integrator.h:35,
                 from /home/lvotapka/openmm/openmmapi/include/openmm/BrownianIntegrator.h:35,
                 from /home/lvotapka/openmm/openmmapi/include/OpenMM.h:36,
                 from src/swig_doxygen/OpenMMSwig.cxx:7346:
/home/lvotapka/openmm/openmmapi/include/openmm/Vec3.h: At global scope:
/home/lvotapka/openmm/openmmapi/include/openmm/Vec3.h:160:13: warning: ‘OpenMM::Vec3 OpenMM::operator*(double, OpenMM::Vec3)’ defined but not used [-Wunused-function]
 static Vec3 operator*(double lhs, Vec3 rhs) {
             ^~~~~~~~
error: command '/usr/bin/g++' failed with exit code 1
```
Upon some experimentation, I was able to get past these errors by installing numpy 1.26. Perhaps that's because I need to try and install a later version of OpenMM. I just wanted to let everyone know.

**Comment by peastman** [comment]
This was fixed in #4622.  It works correctly with numpy 2 in 8.2 beta.

**Comment by lvotapka** [comment]
Alright thanks @peastman, if nothing else it will show other people what might be going wrong if they get the same error.
