### PR TITLE
Fix computeNonbonded hang on the HIP platform

### PR DESCRIPTION
**Pull request by ex-rzr**
`computeNonbonded` hangs in some tests (without neighbor list)  on the HIP platform
Reproducible on ROCm 6.4 and 6.4.1 (maybe on older versions too) on various architectures (both CDNA and RDNA).

Affected tests:
* TestHipATMForce
* TestHipMonteCarloBarostat
* TestHipNonbondedForce
* TestHipVirtualSites

Disassembly shows that the compiler splits branches of `if (skipBase+tgx < NUM_TILES_WITH_EXCLUSIONS)` and does
`SHFL(skipTiles, TILE_SIZE-1) < pos` checks in them separately, even though `__builtin_amdgcn_ds_bpermute` is a convergent function. Apparently in this case not all lanes participate in each call.

Unlike other common or CUDA kernels, the HIP kernel uses shuffles instead of shared memory.
First I fixed this issue by adding `SYNC_WARPS` at the end of the loop to ensure that the check `SHFL(skipTiles, TILE_SIZE-1) < pos` stays convergent, this helped.
But then I simplified the code even more with ballot.

### CODE REVIEW

**Comment by peastman** [comment]
All four of those tests are passing for me.  That's on a RX 5700 XT with ROCm 6.2.  I tried to update to 6.4.1, but I can't get it to install.  When I execute `sudo apt install ./amdgpu-install_6.4.60401-1_all.deb`, it fails with the message

```
Building module:
Cleaning build area...(bad exit status: 2)
. /tmp/amd.0tn8LmU2/.env && make -j4 KERNELRELEASE=6.11.0-24-generic TTM_NAME=amdttm SCHED_NAME=amd-sched -C /lib/modules/6.1
1.0-24-generic/build M=/tmp/amd.0tn8LmU2....(bad exit status: 2)
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/amdgpu-dkms.0.crash'
Error! Bad return status for module build on kernel: 6.11.0-24-generic (x86_64)
Consult /var/lib/dkms/amdgpu/6.8.5-2041575.24.04/build/make.log for more information.
```

Checking `make.log`, there are a lot of compilation errors.  Here is the first one.

```
/tmp/amd.0tn8LmU2/scheduler/./gpu_scheduler_trace.h:60:1: error: macro "__assign_str" passed 2 arguments, but takes just 1
   60 | );
      | ^~             
In file included from ./include/trace/trace_events.h:378:
./include/trace/stages/stage6_event_callback.h:34: note: macro "__assign_str" defined here
   34 | #define __assign_str(dst)                                               \
      | 
/tmp/amd.0tn8LmU2/scheduler/./gpu_scheduler_trace.h: In function ‘do_trace_event_raw_event_drm_sched_job’:
```

This is on Ubuntu 24.04.

**Comment by ex-rzr** [comment]
> All four of those tests are passing for me. That's on a RX 5700 XT with ROCm 6.2.

Yes, I also had no issues in any tests on older versions (<= 6.2, if I remember correctly). But these tests hang on 6.4 and 6.4.1 on all GPUs I have tested (gfx908, 90a, 1030, 1100, 1201).

About the error during ROCm update, I found this thread and this comment: https://github.com/ROCm/ROCm/issues/3870#issuecomment-2655995422

> The solution was to uninstall amdgpu-dkms

Also: https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/native_linux/install-radeon.html#upgrade-to-newer-versions-of-radeon-software-for-linux

> The recommended method to upgrade is to uninstall, followed by an install.
> Radeon Software for Linux does not support in-place upgrades.

**Comment by peastman** [comment]
Thanks!  I removed 6.2 and successfully installed 6.4.1.  But it no longer seems to include any files for OpenCL, even when I specify `--usecase=opencl`.  At least, `libOpenCL.so` is no longer present in `/opt/rocm/lib`.  Has it moved somewhere else?

**Comment by ex-rzr** [comment]
What I found in 6.3 release notes:
https://rocm.docs.amd.com/en/docs-6.3.0/about/release-notes.html#opencl-icd-loader-separated-from-rocm

But I don't see anything about OpenCL on the linked pages about installation...

**Comment by ex-rzr** [comment]
It looks like OpenCL can be installed with package manager: 
https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/package-manager-integration.html

Additional info about the icd loader: https://foldingforum.org/viewtopic.php?t=42803&start=15

**Comment by peastman** [comment]
Yeah, not very helpful instructions!  I managed to compile by [installing the Mesa version](https://kazanas.com/getting-opencl-1-2-to-work-with-amd-gpus-on-ubuntu/) with the command

```
sudo apt install mesa-opencl-icd ocl-icd-libopencl1 ocl-icd-opencl-dev clinfo opencl-headers -y
```

I confirmed the hang with 6.4.1.  I'll try your fix next.

**Comment by peastman** [comment]
I confirmed the fix eliminates the hang.  I'm running the full test suite now.  If everything is ok I'll merge this and build a new release candidate for 8.3.

**Comment by peastman** [comment]
All tests passed.  Thanks for the fix!
