### ISSUE TITLE
ommstuff.cpp errors

### ISSUE THREAD

**Issue by rsdmse** [openmm/openmm#2988]
I came across some errors when compiling OpenMM with AMOEBA (release version 7.5.0) on Ubuntu. I followed the instructions in sections 8.2 and 14.2 in the documentation. A few modifications to the steps in 14.2 had to be made:

1. The link in step 2 doesn't work. Replace `ffe` with `tinker`.
2. The file names in step 3 need to be updated. I downloaded TINKER 7.1.3 and the corresponding modified files from the Downloads section.
3. `OpenMM_INSTALL_DIR` should be `OPENMMDIR`.
4. `make dynamic_openmm.x` doesn't work since the target is `dynamic_omm.x`

Everything worked fine until step 5. When I run `make` I get these errors related to a definition conflict in the header files:

```
g++ -c -O3 -ffast-math -fopenmp -I/usr/local/openmm/include ommstuff.cpp
ommstuff.cpp: In function 'void setupAmoebaVdwForce(OpenMM_System*, FILE*)':
ommstuff.cpp:1922:59: error: too few arguments to function 'int OpenMM_AmoebaVdwForce_addParticle(OpenMM_AmoebaVdwForce*, int, double, double, double, OpenMM_Boolean)'
 1922 |                                            vdw__.kred[ii] );
      |                                                           ^
In file included from ommstuff.cpp:53:
/usr/local/openmm/include/AmoebaOpenMMCWrapper.h:57:33: note: declared here
   57 | extern OPENMM_EXPORT_AMOEBA int OpenMM_AmoebaVdwForce_addParticle(OpenMM_AmoebaVdwForce* target, int parentIndex, double sigma, double epsilon, double reductionFactor, OpenMM_Boolean isAlchemical);
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ommstuff.cpp: In function 'void setupMonteCarloBarostat(OpenMM_System*, FILE*)':
ommstuff.cpp:1983:97: error: 'OpenMM_MonteCarloBarostat_getTemperature' was not declared in this scope; did you mean 'OpenMM_MonteCarloBarostat_Temperature'?
 1983 |         (void) fprintf( log, "                                      Temperature: %15.7e K\n",   OpenMM_MonteCarloBarostat_getTemperature( monteCarloBarostat ) );
      |
```

Is there a patch that I can use?

**Comment by rsdmse** [comment]
I just noticed that in the `0README` of `tinker-plugin`:
> The Makefile assumes OpenMM 6.2.0 is present ...
and that the date of the package is 2015. I assume this will only work with OpenMM 6.2.0 then?

**Comment by peastman** [comment]
The integration between OpenMM and Tinker was taken over by the Tinker developers years ago.  The files you're looking at are a very old version that is long out of date.  You can find information about the current version at https://github.com/TinkerTools/tinker-openmm.
