### ISSUE TITLE
Commit 641389f726 seems to have broken Python API build on OS X

### ISSUE THREAD

**Issue by jchodera** [openmm/openmm#194]
Commit 641389f726 seems to have broken Python API build on my OS X 10.8 machine:

```
building 'simtk.openmm._openmm' extension
creating build/temp.macosx-10.6-x86_64-2.7
creating build/temp.macosx-10.6-x86_64-2.7/src
creating build/temp.macosx-10.6-x86_64-2.7/src/swig_doxygen
gcc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -DNDEBUG -g -O3 -arch x86_64 -DMAJOR_VERSION=5 -DMINOR_VERSION=2 -I/Users/choderaj/code/openmm/install/include -I/Applications/Canopy.app/appdata/canopy-1.1.0.1371.macosx-x86_64/Canopy.app/Contents/include/python2.7 -c src/swig_doxygen/OpenMMSwig.cxx -o build/temp.macosx-10.6-x86_64-2.7/src/swig_doxygen/OpenMMSwig.o
src/swig_doxygen/OpenMMSwig.cxx:64569:11: error: no type named 'ThreadPool' in namespace 'OpenMM'
  OpenMM::ThreadPool *arg1 = (OpenMM::ThreadPool *) 0 ;
  ~~~~~~~~^
src/swig_doxygen/OpenMMSwig.cxx:64569:39: error: no member named 'ThreadPool' in namespace 'OpenMM'
  OpenMM::ThreadPool *arg1 = (OpenMM::ThreadPool *) 0 ;
                              ~~~~~~~~^
src/swig_doxygen/OpenMMSwig.cxx:64569:51: error: expected expression
  OpenMM::ThreadPool *arg1 = (OpenMM::ThreadPool *) 0 ;
                                                  ^
src/swig_doxygen/OpenMMSwig.cxx:64579:36: error: no type named 'ThreadPool' in namespace 'OpenMM'
  arg1 = reinterpret_cast< OpenMM::ThreadPool * >(argp1);
                           ~~~~~~~~^
src/swig_doxygen/OpenMMSwig.cxx:64597:11: error: no type named 'ThreadPool' in namespace 'OpenMM'
  OpenMM::ThreadPool *arg1 = (OpenMM::ThreadPool *) 0 ;
  ~~~~~~~~^
src/swig_doxygen/OpenMMSwig.cxx:64597:39: error: no member named 'ThreadPool' in namespace 'OpenMM'
  OpenMM::ThreadPool *arg1 = (OpenMM::ThreadPool *) 0 ;
                              ~~~~~~~~^
src/swig_doxygen/OpenMMSwig.cxx:64597:51: error: expected expression
  OpenMM::ThreadPool *arg1 = (OpenMM::ThreadPool *) 0 ;
                                                  ^
src/swig_doxygen/OpenMMSwig.cxx:64608:36: error: no type named 'ThreadPool' in namespace 'OpenMM'
  arg1 = reinterpret_cast< OpenMM::ThreadPool * >(argp1);
                           ~~~~~~~~^
src/swig_doxygen/OpenMMSwig.cxx:64611:31: error: no member named 'ThreadPool' in namespace 'OpenMM'
      result = (int)((OpenMM::ThreadPool const *)arg1)->getNumThreads();
                      ~~~~~~~~^
src/swig_doxygen/OpenMMSwig.cxx:64626:11: error: no type named 'ThreadPool' in namespace 'OpenMM'
  OpenMM::ThreadPool *arg1 = (OpenMM::ThreadPool *) 0 ;
  ~~~~~~~~^
src/swig_doxygen/OpenMMSwig.cxx:64626:39: error: no member named 'ThreadPool' in namespace 'OpenMM'
  OpenMM::ThreadPool *arg1 = (OpenMM::ThreadPool *) 0 ;
                              ~~~~~~~~^
src/swig_doxygen/OpenMMSwig.cxx:64626:51: error: expected expression
  OpenMM::ThreadPool *arg1 = (OpenMM::ThreadPool *) 0 ;
                                                  ^
src/swig_doxygen/OpenMMSwig.cxx:64627:3: error: unknown type name 'Task'
  Task *arg2 = 0 ;
  ^
src/swig_doxygen/OpenMMSwig.cxx:64640:36: error: no type named 'ThreadPool' in namespace 'OpenMM'
  arg1 = reinterpret_cast< OpenMM::ThreadPool * >(argp1);
                           ~~~~~~~~^
src/swig_doxygen/OpenMMSwig.cxx:64648:28: error: unknown type name 'Task'
  arg2 = reinterpret_cast< Task * >(argp2);
                           ^
src/swig_doxygen/OpenMMSwig.cxx:64666:11: error: no type named 'ThreadPool' in namespace 'OpenMM'
  OpenMM::ThreadPool *arg1 = (OpenMM::ThreadPool *) 0 ;
  ~~~~~~~~^
src/swig_doxygen/OpenMMSwig.cxx:64666:39: error: no member named 'ThreadPool' in namespace 'OpenMM'
  OpenMM::ThreadPool *arg1 = (OpenMM::ThreadPool *) 0 ;
                              ~~~~~~~~^
src/swig_doxygen/OpenMMSwig.cxx:64666:51: error: expected expression
  OpenMM::ThreadPool *arg1 = (OpenMM::ThreadPool *) 0 ;
                                                  ^
src/swig_doxygen/OpenMMSwig.cxx:64676:36: error: no type named 'ThreadPool' in namespace 'OpenMM'
  arg1 = reinterpret_cast< OpenMM::ThreadPool * >(argp1);
                           ~~~~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
error: command 'gcc' failed with exit status 1
[LSKI1497:openmm/openmm/python] choderaj% python
```
